export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_USER_ITEMS = 'FETCH_USER_ITEMS';
export const FETCH_USER_ITEMS_FAILURE = 'FETCH_USER_ITEMS_FAILURE';
export const FETCH_USER_ITEMS_SUCCESS = 'FETCH_USER_ITEMS_SUCCESS';